name = "ImageReconstruction"
uuid = "d5d0ac58-a118-45a5-925e-339d09fa0c5f"
authors = ["Kevin C. Zimmerman"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
